<?php // Include Here Everything
error_reporting(0);
$_SERVER['page_load_info'] = 'Start of Script: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
session_start(['cookie_lifetime' => 518400]);
$_SERVER['page_load_info'] .= 'Session Started: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
include_once ('database_connection.php');
$_SERVER['page_load_info'] .= 'Database Connected: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
include_once ('function.php');
$_SERVER['page_load_info'] .= 'Functions Loaded: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
include_once ('global.php');
$_SERVER['page_load_info'] .= 'Globals Declared: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
session_write_close();
if ($_SERVER['HTTP_X_REQUESTED_WITH'] != 'XMLHttpRequest') {
	include_once ('header.php');
} else { ?>
	<script>
		$(document).ready(function() { 
			initInputs();
		});
	</script>
<?php }
$_SERVER['page_load_info'] .= 'Header Loaded: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
include_once ('output_functions.php');
$_SERVER['page_load_info'] .= 'Output Declared: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
include_once ('pagination.php');
$_SERVER['page_load_info'] .= 'Pagination Declared: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
include_once ('filter.php');
$_SERVER['page_load_info'] .= 'Filters Built: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
include_once ('email.php');
$_SERVER['page_load_info'] .= 'Email Initialized: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
if ( FOLDER_NAME=='reports' ) {
    include_once ('Reports/report_tiles_function.php');
}
include_once ('mobile_detect.php');
$_SERVER['page_load_info'] .= 'Mobile Detected: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
if($_SESSION['user_preferences']['loaded_time'] + 3600 < time()) {
	session_start(['cookie_lifetime' => 518400]);
	$_SESSION['user_preferences'] = get_user_settings();
	$_SERVER['page_load_info'] .= 'User Settings Updated: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
	$_SESSION['user_preferences']['loaded_time'] = time();
	session_write_close();
}
include_once ('user_font_settings.php');
$_SERVER['page_load_info'] .= 'User Font Initialized: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
if(!($_SESSION['tile_list_updated'] > 0)) {
	$no_display = true;
	include_once('tiles.php');
	unset($no_display);
	$_SERVER['page_load_info'] .= 'Updated Tile List: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
}
if($_SESSION['contactid'] > 0) {
	set_last_active($dbc, $_SESSION['contactid']);
	$_SERVER['page_load_info'] .= 'Activity Noted: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
}
include_once ('reload_cache.php');
$_SERVER['page_load_info'] .= 'Cache Loaded: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";

$rookconnect = get_software_name();
$scale_style = '';
$page_options = mysqli_query($dbc, "SELECT * FROM `page_options` WHERE `php_self`='".filter_var($_SERVER['PHP_SELF'],FILTER_SANITIZE_STRING)."' AND `contactid`='".$_SESSION['contactid']."'");
if(mysqli_num_rows($page_options) > 0) {
	if($page_options = mysqli_fetch_assoc($page_options)) {
		if($page_options['scale_width'] > 0) {
			$scale_style = 'width:'.$page_options['scale_width'].'%;';
		}
	}
}

// Get User's time zone offset
$_SESSION['time_offset'] = '';
$user_regions = get_contact($dbc, $_SESSION['contactid'], 'region');
$user_classes = get_contact($dbc, $_SESSION['contactid'], 'classification');
foreach(array_filter(explode(',',$user_regions)) as $user_region) {
    foreach(explode(',',get_config($dbc, 'contacts_region')) as $i => $region_name) {
        if($region_name == $user_region && $region_name != '') {
            $_SESSION['time_offset'] = explode(',',get_config($dbc, 'region_time_offset'))[$i];
        }
    }
}
foreach(array_filter(explode(',',$user_classes)) as $user_class) {
    foreach(explode(',',get_config($dbc, 'contacts_classification')) as $i => $class_name) {
        if($class_name == $user_class && $class_name != '') {
            $_SESSION['time_offset'] = explode(',',get_config($dbc, 'classification_time_offset'))[$i];
        }
    }
}
$offset = new DateTime();
if(empty($_SESSION['time_offset'])) {
    $_SESSION['time_offset'] = $offset->getOffset();
} else {
    switch($_SESSION['time_offset']) {
        case 'Africa/Abidjan': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Accra': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Addis_Ababa': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Africa/Algiers': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Asmara': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Africa/Bamako': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Bangui': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Banjul': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Bissau': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Blantyre': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Brazzaville': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Bujumbura': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Cairo': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Casablanca': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Africa/Ceuta': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Africa/Conakry': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Dakar': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Dar_es_Salaam': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Africa/Djibouti': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Africa/Douala': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/El_Aaiun': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Africa/Freetown': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Gaborone': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Harare': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Johannesburg': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Juba': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Africa/Kampala': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Africa/Khartoum': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Kigali': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Kinshasa': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Lagos': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Libreville': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Lome': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Luanda': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Lubumbashi': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Lusaka': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Malabo': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Maputo': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Maseru': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Mbabane': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Mogadishu': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Africa/Monrovia': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Nairobi': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Africa/Ndjamena': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Niamey': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Nouakchott': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Ouagadougou': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Porto-Novo': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Sao_Tome': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Timbuktu': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Africa/Tripoli': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Africa/Tunis': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Africa/Windhoek': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'America/Adak': $_SESSION['time_offset'] = date('I') ? -36000 : -32400; break;
        case 'America/Anchorage': $_SESSION['time_offset'] = date('I') ? -32400 : -28800; break;
        case 'America/Anguilla': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Antigua': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Araguaina': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Buenos_Aires': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Catamarca': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/ComodRivadavia': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Cordoba': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Jujuy': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/La_Rioja': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Mendoza': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Rio_Gallegos': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Salta': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/San_Juan': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/San_Luis': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Tucuman': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Argentina/Ushuaia': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Aruba': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Asuncion': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Atikokan': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Atka': $_SESSION['time_offset'] = date('I') ? -36000 : -32400; break;
        case 'America/Bahia': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Bahia_Banderas': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Barbados': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Belem': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Belize': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'America/Blanc-Sablon': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Boa_Vista': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Bogota': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Boise': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Buenos_Aires': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Cambridge_Bay': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Campo_Grande': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Cancun': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Caracas': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Catamarca': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Cayenne': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Cayman': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Chicago': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Chihuahua': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Coral_Harbour': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Cordoba': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Costa_Rica': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'America/Creston': $_SESSION['time_offset'] = date('I') ? -25200 : -25200; break;
        case 'America/Cuiaba': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Curacao': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Danmarkshavn': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'America/Dawson': $_SESSION['time_offset'] = date('I') ? -28800 : -25200; break;
        case 'America/Dawson_Creek': $_SESSION['time_offset'] = date('I') ? -25200 : -25200; break;
        case 'America/Denver': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Detroit': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Dominica': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Edmonton': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Eirunepe': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/El_Salvador': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'America/Ensenada': $_SESSION['time_offset'] = date('I') ? -28800 : -25200; break;
        case 'America/Fort_Nelson': $_SESSION['time_offset'] = date('I') ? -25200 : -25200; break;
        case 'America/Fort_Wayne': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Fortaleza': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Glace_Bay': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Godthab': $_SESSION['time_offset'] = date('I') ? -10800 : -7200; break;
        case 'America/Goose_Bay': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Grand_Turk': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Grenada': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Guadeloupe': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Guatemala': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'America/Guayaquil': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Guyana': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Halifax': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Havana': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Hermosillo': $_SESSION['time_offset'] = date('I') ? -25200 : -25200; break;
        case 'America/Indiana/Indianapolis': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Indiana/Knox': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Indiana/Marengo': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Indiana/Petersburg': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Indiana/Tell_City': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Indiana/Vevay': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Indiana/Vincennes': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Indiana/Winamac': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Indianapolis': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Inuvik': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Iqaluit': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Jamaica': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Jujuy': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Juneau': $_SESSION['time_offset'] = date('I') ? -32400 : -28800; break;
        case 'America/Kentucky/Louisville': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Kentucky/Monticello': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Knox_IN': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Kralendijk': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/La_Paz': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Lima': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Los_Angeles': $_SESSION['time_offset'] = date('I') ? -28800 : -25200; break;
        case 'America/Louisville': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Lower_Princes': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Maceio': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Managua': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'America/Manaus': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Marigot': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Martinique': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Matamoros': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Mazatlan': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Mendoza': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Menominee': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Merida': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Metlakatla': $_SESSION['time_offset'] = date('I') ? -32400 : -28800; break;
        case 'America/Mexico_City': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Miquelon': $_SESSION['time_offset'] = date('I') ? -10800 : -7200; break;
        case 'America/Moncton': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Monterrey': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Montevideo': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Montreal': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Montserrat': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Nassau': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/New_York': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Nipigon': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Nome': $_SESSION['time_offset'] = date('I') ? -32400 : -28800; break;
        case 'America/Noronha': $_SESSION['time_offset'] = date('I') ? -7200 : -7200; break;
        case 'America/North_Dakota/Beulah': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/North_Dakota/Center': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/North_Dakota/New_Salem': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Ojinaga': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Panama': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Pangnirtung': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Paramaribo': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Phoenix': $_SESSION['time_offset'] = date('I') ? -25200 : -25200; break;
        case 'America/Port_of_Spain': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Port-au-Prince': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Porto_Acre': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Porto_Velho': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Puerto_Rico': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Punta_Arenas': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Rainy_River': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Rankin_Inlet': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Recife': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Regina': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'America/Resolute': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Rio_Branco': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'America/Rosario': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Santa_Isabel': $_SESSION['time_offset'] = date('I') ? -28800 : -25200; break;
        case 'America/Santarem': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'America/Santiago': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Santo_Domingo': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Sao_Paulo': $_SESSION['time_offset'] = date('I') ? -10800 : -7200; break;
        case 'America/Scoresbysund': $_SESSION['time_offset'] = date('I') ? -3600 : 0; break;
        case 'America/Shiprock': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'America/Sitka': $_SESSION['time_offset'] = date('I') ? -32400 : -28800; break;
        case 'America/St_Barthelemy': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/St_Johns': $_SESSION['time_offset'] = date('I') ? -12600 : -9000; break;
        case 'America/St_Kitts': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/St_Lucia': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/St_Thomas': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/St_Vincent': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Swift_Current': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'America/Tegucigalpa': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'America/Thule': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'America/Thunder_Bay': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Tijuana': $_SESSION['time_offset'] = date('I') ? -28800 : -25200; break;
        case 'America/Toronto': $_SESSION['time_offset'] = date('I') ? -18000 : -14400; break;
        case 'America/Tortola': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Vancouver': $_SESSION['time_offset'] = date('I') ? -28800 : -25200; break;
        case 'America/Virgin': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'America/Whitehorse': $_SESSION['time_offset'] = date('I') ? -28800 : -25200; break;
        case 'America/Winnipeg': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'America/Yakutat': $_SESSION['time_offset'] = date('I') ? -32400 : -28800; break;
        case 'America/Yellowknife': $_SESSION['time_offset'] = date('I') ? -25200 : -21600; break;
        case 'Antarctica/Casey': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Antarctica/Davis': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Antarctica/DumontDUrville': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Antarctica/Macquarie': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Antarctica/Mawson': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Antarctica/McMurdo': $_SESSION['time_offset'] = date('I') ? 43200 : 46800; break;
        case 'Antarctica/Palmer': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'Antarctica/Rothera': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'Antarctica/South_Pole': $_SESSION['time_offset'] = date('I') ? 43200 : 46800; break;
        case 'Antarctica/Syowa': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Antarctica/Troll': $_SESSION['time_offset'] = date('I') ? 0 : 7200; break;
        case 'Antarctica/Vostok': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Arctic/Longyearbyen': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Asia/Aden': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Asia/Almaty': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Amman': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Asia/Anadyr': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Asia/Aqtau': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Aqtobe': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Ashgabat': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Ashkhabad': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Atyrau': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Baghdad': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Asia/Bahrain': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Asia/Baku': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Asia/Bangkok': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Barnaul': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Beirut': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Asia/Bishkek': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Brunei': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Calcutta': $_SESSION['time_offset'] = date('I') ? 19800 : 19800; break;
        case 'Asia/Chita': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Asia/Choibalsan': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Chongqing': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Chungking': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Colombo': $_SESSION['time_offset'] = date('I') ? 19800 : 19800; break;
        case 'Asia/Dacca': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Damascus': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Asia/Dhaka': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Dili': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Asia/Dubai': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Asia/Dushanbe': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Famagusta': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Asia/Gaza': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Asia/Harbin': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Hebron': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Asia/Ho_Chi_Minh': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Hong_Kong': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Hovd': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Irkutsk': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Istanbul': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Asia/Jakarta': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Jayapura': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Asia/Jerusalem': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Asia/Kabul': $_SESSION['time_offset'] = date('I') ? 16200 : 16200; break;
        case 'Asia/Kamchatka': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Asia/Karachi': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Kashgar': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Kathmandu': $_SESSION['time_offset'] = date('I') ? 20700 : 20700; break;
        case 'Asia/Katmandu': $_SESSION['time_offset'] = date('I') ? 20700 : 20700; break;
        case 'Asia/Khandyga': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Asia/Kolkata': $_SESSION['time_offset'] = date('I') ? 19800 : 19800; break;
        case 'Asia/Krasnoyarsk': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Kuala_Lumpur': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Kuching': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Kuwait': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Asia/Macao': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Macau': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Magadan': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Asia/Makassar': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Manila': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Muscat': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Asia/Novokuznetsk': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Novosibirsk': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Omsk': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Oral': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Phnom_Penh': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Pontianak': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Pyongyang': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Asia/Qatar': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Asia/Qyzylorda': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Rangoon': $_SESSION['time_offset'] = date('I') ? 23400 : 23400; break;
        case 'Asia/Riyadh': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Asia/Saigon': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Sakhalin': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Asia/Samarkand': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Seoul': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Asia/Shanghai': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Singapore': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Srednekolymsk': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Asia/Taipei': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Tashkent': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Tbilisi': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Asia/Tehran': $_SESSION['time_offset'] = date('I') ? 12600 : 16200; break;
        case 'Asia/Tel_Aviv': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Asia/Thimbu': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Thimphu': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Tokyo': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Asia/Tomsk': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Ujung_Pandang': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Ulaanbaatar': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Ulan_Bator': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Asia/Urumqi': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Asia/Ust-Nera': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Asia/Vientiane': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Asia/Vladivostok': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Asia/Yakutsk': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Asia/Yangon': $_SESSION['time_offset'] = date('I') ? 23400 : 23400; break;
        case 'Asia/Yekaterinburg': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Asia/Yerevan': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Atlantic/Azores': $_SESSION['time_offset'] = date('I') ? -3600 : 0; break;
        case 'Atlantic/Bermuda': $_SESSION['time_offset'] = date('I') ? -14400 : -10800; break;
        case 'Atlantic/Canary': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Atlantic/Cape_Verde': $_SESSION['time_offset'] = date('I') ? -3600 : -3600; break;
        case 'Atlantic/Faeroe': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Atlantic/Faroe': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Atlantic/Jan_Mayen': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Atlantic/Madeira': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Atlantic/Reykjavik': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Atlantic/South_Georgia': $_SESSION['time_offset'] = date('I') ? -7200 : -7200; break;
        case 'Atlantic/St_Helena': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Atlantic/Stanley': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'Australia/Adelaide': $_SESSION['time_offset'] = date('I') ? 34200 : 37800; break;
        case 'Australia/Brisbane': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Australia/Broken_Hill': $_SESSION['time_offset'] = date('I') ? 34200 : 37800; break;
        case 'Australia/Canberra': $_SESSION['time_offset'] = date('I') ? 36000 : 39600; break;
        case 'Australia/Currie': $_SESSION['time_offset'] = date('I') ? 36000 : 39600; break;
        case 'Australia/Darwin': $_SESSION['time_offset'] = date('I') ? 34200 : 34200; break;
        case 'Australia/Eucla': $_SESSION['time_offset'] = date('I') ? 31500 : 31500; break;
        case 'Australia/Hobart': $_SESSION['time_offset'] = date('I') ? 36000 : 39600; break;
        case 'Australia/Lindeman': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Australia/Lord_Howe': $_SESSION['time_offset'] = date('I') ? 37800 : 39600; break;
        case 'Australia/Melbourne': $_SESSION['time_offset'] = date('I') ? 36000 : 39600; break;
        case 'Australia/Perth': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Australia/Sydney': $_SESSION['time_offset'] = date('I') ? 36000 : 39600; break;
        case 'Australia/Yancowinna': $_SESSION['time_offset'] = date('I') ? 34200 : 37800; break;
        case 'Etc/GMT': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Etc/GMT+0': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Etc/GMT+1': $_SESSION['time_offset'] = date('I') ? -3600 : -3600; break;
        case 'Etc/GMT+10': $_SESSION['time_offset'] = date('I') ? -36000 : -36000; break;
        case 'Etc/GMT+11': $_SESSION['time_offset'] = date('I') ? -39600 : -39600; break;
        case 'Etc/GMT+12': $_SESSION['time_offset'] = date('I') ? -43200 : -43200; break;
        case 'Etc/GMT+2': $_SESSION['time_offset'] = date('I') ? -7200 : -7200; break;
        case 'Etc/GMT+3': $_SESSION['time_offset'] = date('I') ? -10800 : -10800; break;
        case 'Etc/GMT+4': $_SESSION['time_offset'] = date('I') ? -14400 : -14400; break;
        case 'Etc/GMT+5': $_SESSION['time_offset'] = date('I') ? -18000 : -18000; break;
        case 'Etc/GMT+6': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'Etc/GMT+7': $_SESSION['time_offset'] = date('I') ? -25200 : -25200; break;
        case 'Etc/GMT+8': $_SESSION['time_offset'] = date('I') ? -28800 : -28800; break;
        case 'Etc/GMT+9': $_SESSION['time_offset'] = date('I') ? -32400 : -32400; break;
        case 'Etc/GMT0': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Etc/GMT-0': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Etc/GMT-1': $_SESSION['time_offset'] = date('I') ? 3600 : 3600; break;
        case 'Etc/GMT-10': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Etc/GMT-11': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Etc/GMT-12': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Etc/GMT-13': $_SESSION['time_offset'] = date('I') ? 46800 : 46800; break;
        case 'Etc/GMT-14': $_SESSION['time_offset'] = date('I') ? 50400 : 50400; break;
        case 'Etc/GMT-2': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Etc/GMT-3': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Etc/GMT-4': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Etc/GMT-5': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Etc/GMT-6': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Etc/GMT-7': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Etc/GMT-8': $_SESSION['time_offset'] = date('I') ? 28800 : 28800; break;
        case 'Etc/GMT-9': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Etc/UTC': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Europe/Amsterdam': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Andorra': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Astrakhan': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Europe/Athens': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Belfast': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Europe/Belgrade': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Berlin': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Bratislava': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Brussels': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Bucharest': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Budapest': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Busingen': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Chisinau': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Copenhagen': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Dublin': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Europe/Gibraltar': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Guernsey': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Europe/Helsinki': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Isle_of_Man': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Europe/Istanbul': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Europe/Jersey': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Europe/Kaliningrad': $_SESSION['time_offset'] = date('I') ? 7200 : 7200; break;
        case 'Europe/Kiev': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Kirov': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Europe/Lisbon': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Europe/Ljubljana': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/London': $_SESSION['time_offset'] = date('I') ? 0 : 3600; break;
        case 'Europe/Luxembourg': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Madrid': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Malta': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Mariehamn': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Minsk': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Europe/Monaco': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Moscow': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Europe/Nicosia': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Oslo': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Paris': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Podgorica': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Prague': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Riga': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Rome': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Samara': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Europe/San_Marino': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Sarajevo': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Saratov': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Europe/Simferopol': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Europe/Skopje': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Sofia': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Stockholm': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Tallinn': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Tirane': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Tiraspol': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Ulyanovsk': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Europe/Uzhgorod': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Vaduz': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Vatican': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Vienna': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Vilnius': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Volgograd': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Europe/Warsaw': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Zagreb': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'Europe/Zaporozhye': $_SESSION['time_offset'] = date('I') ? 7200 : 10800; break;
        case 'Europe/Zurich': $_SESSION['time_offset'] = date('I') ? 3600 : 7200; break;
        case 'GMT': $_SESSION['time_offset'] = date('I') ? 0 : 0; break;
        case 'Indian/Antananarivo': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Indian/Chagos': $_SESSION['time_offset'] = date('I') ? 21600 : 21600; break;
        case 'Indian/Christmas': $_SESSION['time_offset'] = date('I') ? 25200 : 25200; break;
        case 'Indian/Cocos': $_SESSION['time_offset'] = date('I') ? 23400 : 23400; break;
        case 'Indian/Comoro': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Indian/Kerguelen': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Indian/Mahe': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Indian/Maldives': $_SESSION['time_offset'] = date('I') ? 18000 : 18000; break;
        case 'Indian/Mauritius': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Indian/Mayotte': $_SESSION['time_offset'] = date('I') ? 10800 : 10800; break;
        case 'Indian/Reunion': $_SESSION['time_offset'] = date('I') ? 14400 : 14400; break;
        case 'Pacific/Apia': $_SESSION['time_offset'] = date('I') ? 46800 : 50400; break;
        case 'Pacific/Auckland': $_SESSION['time_offset'] = date('I') ? 43200 : 46800; break;
        case 'Pacific/Bougainville': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Pacific/Chatham': $_SESSION['time_offset'] = date('I') ? 45900 : 49500; break;
        case 'Pacific/Chuuk': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Pacific/Easter': $_SESSION['time_offset'] = date('I') ? -21600 : -18000; break;
        case 'Pacific/Efate': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Pacific/Enderbury': $_SESSION['time_offset'] = date('I') ? 46800 : 46800; break;
        case 'Pacific/Fakaofo': $_SESSION['time_offset'] = date('I') ? 46800 : 46800; break;
        case 'Pacific/Fiji': $_SESSION['time_offset'] = date('I') ? 43200 : 46800; break;
        case 'Pacific/Funafuti': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Pacific/Galapagos': $_SESSION['time_offset'] = date('I') ? -21600 : -21600; break;
        case 'Pacific/Gambier': $_SESSION['time_offset'] = date('I') ? -32400 : -32400; break;
        case 'Pacific/Guadalcanal': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Pacific/Guam': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Pacific/Honolulu': $_SESSION['time_offset'] = date('I') ? -36000 : -36000; break;
        case 'Pacific/Johnston': $_SESSION['time_offset'] = date('I') ? -36000 : -36000; break;
        case 'Pacific/Kiritimati': $_SESSION['time_offset'] = date('I') ? 50400 : 50400; break;
        case 'Pacific/Kosrae': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Pacific/Kwajalein': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Pacific/Majuro': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Pacific/Marquesas': $_SESSION['time_offset'] = date('I') ? -34200 : -34200; break;
        case 'Pacific/Midway': $_SESSION['time_offset'] = date('I') ? -39600 : -39600; break;
        case 'Pacific/Nauru': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Pacific/Niue': $_SESSION['time_offset'] = date('I') ? -39600 : -39600; break;
        case 'Pacific/Norfolk': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Pacific/Noumea': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Pacific/Pago_Pago': $_SESSION['time_offset'] = date('I') ? -39600 : -39600; break;
        case 'Pacific/Palau': $_SESSION['time_offset'] = date('I') ? 32400 : 32400; break;
        case 'Pacific/Pitcairn': $_SESSION['time_offset'] = date('I') ? -28800 : -28800; break;
        case 'Pacific/Pohnpei': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Pacific/Ponape': $_SESSION['time_offset'] = date('I') ? 39600 : 39600; break;
        case 'Pacific/Port_Moresby': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Pacific/Rarotonga': $_SESSION['time_offset'] = date('I') ? -36000 : -36000; break;
        case 'Pacific/Saipan': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Pacific/Samoa': $_SESSION['time_offset'] = date('I') ? -39600 : -39600; break;
        case 'Pacific/Tahiti': $_SESSION['time_offset'] = date('I') ? -36000 : -36000; break;
        case 'Pacific/Tarawa': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Pacific/Tongatapu': $_SESSION['time_offset'] = date('I') ? 46800 : 50400; break;
        case 'Pacific/Truk': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
        case 'Pacific/Wake': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Pacific/Wallis': $_SESSION['time_offset'] = date('I') ? 43200 : 43200; break;
        case 'Pacific/Yap': $_SESSION['time_offset'] = date('I') ? 36000 : 36000; break;
    }
}
$offset = sprintf('%d:%02d', $offset->getOffset() / 3600, ($offset->getOffset() / 60) % 60);
$offset = $dbc->prepare("SET time_zone='$offset'");
$offset->execute();

if(strpos_any !== FALSE)
$_SERVER['page_load_info'] .= 'Start of Page: '.number_format(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'],5)."\n";
if(get_config($dbc, 'timesheet_force_end_midnight') > 0 && strtotime(get_config($dbc, 'timesheet_midnight_last_ended')) < strtotime(date('Y-m-d'))) {
	include_once('../Calendar/calendar_functions_inc.php');
	$midnight_end = true;
	$end_time_list = mysqli_query($dbc, "SELECT `contacts`.`contactid`, `time_cards`.`date`, `time_cards`.`time_cards_id` FROM `contacts` LEFT JOIN `time_cards` ON `contacts`.`contactid` = `time_cards`.`staff` WHERE `contacts`.`category` IN (".STAFF_CATS.") AND ".STAFF_CATS_HIDE_QUERY." AND `contacts`.`status`>0 AND `contacts`.`deleted`=0 AND `timer_start` > 0 AND `time_cards`.`deleted`=0 AND `time_cards`.`staff` > 0 AND `type_of_time`='day_tracking' AND `date` != '".date('Y-m-d')."'");
	while($row = mysqli_fetch_assoc($end_time_list)) {
		$date = $row['date'];
		$day_of_week = date('l', strtotime($date));
		$time = strtotime($date.' 23:59:59');
		$hour = date('H:i', $time);
		$comment = 'Auto checked out after Midnight.';
		$time_minimum = get_config($dbc, 'ticket_min_hours');
		$time_interval = get_config($dbc, 'timesheet_hour_intervals');
		$highlight_query = ", `highlight`=1";
		$midnight_query = " AND `date` = '".$date."'";
		$id_query = " AND `time_cards_id` = '".$row['time_cards_id']."'";

		$staff = $row['contactid'];
		include('../Timesheet/end_day.php');
	}
	set_config($dbc, 'timesheet_midnight_last_ended', date('Y-m-d'));
}
?>